package metadata

// OriginIngressGateway marks xDS resources generated by this plugin.
const (
	OriginIngressGateway       = "ingress-gateway"
	PluginName                 = "ingress-gateway"
	ProfileIngressGatewayProxy = "ingress-gateway-proxy"
)
