package metadata

// OriginGlobalLoadBalancer marks xDS resources generated by this plugin.
const (
	OriginGlobalLoadBalancer       = "global-load-balancer"
	PluginName                     = "global-load-balancer"
	ProfileGlobalLoadBalancerProxy = "global-load-balancer-proxy"
)
